version: '2'
services:
  appServer:
    image: sqlfiddle:appServer
    ports:
    - "5005:5005"
    extra_hosts:
    - "sqlserver2014Host:192.168.99.101"
    - "oracle11gHost:192.168.99.101"
  varnish:
    build:
      context: ./varnish
    image: sqlfiddle:varnish
    links:
    - "appServer"
    environment:
    - VARNISH_BACKEND_HOST=appServer
    - VARNISH_BACKEND_PORT=8080
    ports:
    - "8080:8080"
  appDatabase:
    build:
      context: ./appDatabase
    image: sqlfiddle:appDatabase
  postgresql93Host:
    build:
      context: ./postgresql93Host
    image: sqlfiddle:postgresql93Host
  postgresql96Host:
    build:
      context: ./postgresql96Host
    image: sqlfiddle:postgresql96Host
  mysql56Host:
    build:
      context: ./mysql56Host
    image: sqlfiddle:mysql56Host
