version: '2'
services:
  appServer:
    volumes:
    - ./appServer/target/docker:/usr/verticles
    image: sqlfiddle:appServer
    ports:
    - "8081:8080"
    - "5005:5005"
    environment:
      - VERTX_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true
  varnish:
    build:
      context: ./varnish
    image: sqlfiddle:varnish
    links:
    - "appServer"
    environment:
    - VARNISH_BACKEND_HOST=appServer
    - VARNISH_BACKEND_PORT=8080
    ports:
    - "8080:8080"
  appDatabase:
    build:
      context: ./appDatabase
    image: sqlfiddle:appDatabase
  postgresql93Host:
    build:
      context: ./postgresql93Host
    image: sqlfiddle:postgresql93Host
  postgresql96Host:
    build:
      context: ./postgresql96Host
    image: sqlfiddle:postgresql96Host
  mysql56Host:
    build:
      context: ./mysql56Host
    image: sqlfiddle:mysql56Host
  mssql2017Host:
    build:
      context: ./mssql2017Host
    image: sqlfiddle:mssql2017Host
  oracle11gHost:
    build:
      context: ./oracle11gHost
    shm_size: 1G
    image: sqlfiddle:oracle11gHost
