version: '2'
services:
  appServer:
    image: sqlfiddle:appServer
    ports:
    - "8080:8080"
    links:
    - appDatabase
    - postgresqlHost
    - mysqlHost
  appDatabase:
    build:
      context: ./appDatabase
    image: sqlfiddle:appDatabase
  postgresqlHost:
    build:
      context: ./postgresqlHost
    image: sqlfiddle:postgresqlHost
  mysqlHost:
    build:
      context: ./mysqlHost
    image: sqlfiddle:mysqlHost
