
# login with aws ecr get-login-password | docker login --username AWS --password-stdin $EXTERNAL_REGISTRY

registryPrefix: 321080263678.dkr.ecr.us-west-2.amazonaws.com/sqlfiddle

mssql2017Version: 1.0.3
oracle11gVersion: 1.0.3

sqlfiddleOpenCore:
  appServerReplicas: 2
  appServerMemory: 1024Mi
  appServerImage: appserverextended
  isLocal: false
  registryPrefix: 321080263678.dkr.ecr.us-west-2.amazonaws.com/sqlfiddle
  appDatabaseIP: sqlfiddle.cq2t9zmnkkgq.us-west-2.rds.amazonaws.com
  appServerVersion: 2.0.4
  varnishVersion: 1.0.0
  hostMonitorVersion: 2.0.0
  mysql56Version: 1.0.1
  postgresql93Version: 1.0.1
  postgresql96Version: 1.0.1
