apiVersion: v1
kind: Pod
metadata:
  namespace: sqlfiddle
  name: hostmonitor
spec:
  containers:
    - image: {{ .Values.registryPrefix }}/sqlfiddle:hostMonitor
      imagePullPolicy: IfNotPresent
      name: hostmonitor
      ports:
        - containerPort: 5432
          protocol: TCP
      resources:
          requests:
            memory: "64Mi"
