{{ if .Values.isLocal }}
apiVersion: v1
kind: Pod
metadata:
  namespace: sqlfiddle
  name: appdatabase
  labels:
    role: appdatabase
spec:
  containers:
    - image: sqlfiddle/appdatabase:latest
      imagePullPolicy: IfNotPresent
      name: appdatabase
      ports:
        - containerPort: 5432
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  namespace: sqlfiddle
  name: appdatabase
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    role: appdatabase
{{ else }}
kind: Service
apiVersion: v1
metadata:
  namespace: sqlfiddle
  name: appdatabase
spec:
  type: ExternalName
  externalName: {{ .Values.appDatabaseIP }}
{{ end }}
