apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  namespace: sqlfiddle
  name: appservers
spec:
  replicas: 2
  template:
    metadata:
      labels:
        role: appserver
    spec:
    {{ if .Values.appDatabaseIP }}
      initContainers:
      - name: wait-for-repo
        image: "groundnuty/k8s-wait-for:0.3"
        imagePullPolicy: IfNotPresent
        args: [ "pod", "-l", "role=appdatabase" ]
    {{ end }}
      containers:
        - image: {{ .Values.registryPrefix }}/{{ .Values.appServerImage }}:{{ .Values.appServerVersion }}
          imagePullPolicy: IfNotPresent
          name: appserver
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources:
              requests:
                memory: "1024Mi"
          env:
            - name: VERTX_OPTS
              value: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Xmx960m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Dvertx.disableFileCaching=true -Dvertx.disableFileCPResolving=true"
          readinessProbe:
            httpGet:
              path: /backend/dbTypes
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 20
        - image: sqlfiddle/varnish:{{ .Values.varnishVersion }}
          imagePullPolicy: IfNotPresent
          name: varnish
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
          - name: VARNISH_BACKEND_HOST
            value: "localhost"
          - name: VARNISH_BACKEND_PORT
            value: "8081"
          resources:
              requests:
                memory: "128Mi"
---
kind: Service
apiVersion: v1
metadata:
  namespace: sqlfiddle
  name: appserver-service
spec:
{{ if .Values.isLocal }}{{ else }}
  type: LoadBalancer
{{ end }}
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    role: appserver
{{ if .Values.isLocal }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: sqlfiddle
  name: ingress
spec:
  backend:
    serviceName: appserver-service
    servicePort: 80
{{ end }}
