apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sqlfiddle
  name: mysql56
spec:
  selector:
    matchLabels:
      type: mysql56
  replicas: 1
  template:
    metadata:
      labels:
        type: mysql56
    spec:
      containers:
        - image: sqlfiddle/mysql56host:{{ .Values.mysql56Version }}
          imagePullPolicy: IfNotPresent
          name: mysql56
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
              requests:
                memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - "/ready.sh"
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  namespace: sqlfiddle
  name: mysql56-service
  labels:
    role: host
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: database
  selector:
    type: mysql56
