apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sqlfiddle
  name: postgresql96
spec:
  selector:
    matchLabels:
      type: postgresql96
  replicas: 1
  template:
    metadata:
      labels:
        type: postgresql96
    spec:
      containers:
        - image: sqlfiddle/postgresql96host:{{ .Values.postgresql96Version }}
          imagePullPolicy: IfNotPresent
          name: postgresql96
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
              requests:
                memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - "/ready.sh"
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - "/ready.sh"
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  namespace: sqlfiddle
  name: postgresql96-service
  labels:
    role: host
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: database
  selector:
    type: postgresql96
