apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  namespace: sqlfiddle
  name: postgresql93
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: postgresql93
    spec:
      containers:
        - image: sqlfiddle/postgresql93host:latest
          imagePullPolicy: IfNotPresent
          name: postgresql93
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
              requests:
                memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - "/ready.sh"
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  namespace: sqlfiddle
  name: postgresql93-service
  labels:
    role: host
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: database
  selector:
    type: postgresql93
