apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: oracle11g
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: oracle11g
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - image: sqlfiddle:oracle11gHost
          imagePullPolicy: IfNotPresent
          name: oracle11g
          ports:
            - containerPort: 1521
              protocol: TCP
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          resources:
              requests:
                memory: "512Mi"
          readinessProbe:
            exec:
              command:
                - "/ready.sh"
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - "/live.sh"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 180
---
kind: Service
apiVersion: v1
metadata:
  name: oracle11g-service
  labels:
    role: host
spec:
  clusterIP: None
  ports:
    - port: 1521
      name: database
  selector:
    type: oracle11g
